project:
  type: website
  output-dir: docs
  resources:
    - styles.css
    - allow-html.html

website:
  title: "Stephen's Engineering Portfolio"
  navbar: false   # weâ€™re using the circuit diagram instead

format:
  html:
    css: styles.css
    smooth-scroll: true
    html-math-method: katex
    include-in-header: allow-html.html